#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname $0)/config"

[[ -f "$EMAILS_FILE" ]] || exit 0

APP="$1"
HOSTNAME=$(hostname -f)
URL=$(dokku url $APP)

dokku_log_info1 "Sending emails for $APP"

while read email; do
  dokku_log_info2_quiet "-----> Sending email to $email"

  MESSAGE="Deployed $APP to $HOSTNAME via $URL"
  if ! echo "$MESSAGE" | mail -s "Successful Dokku Deployment" "$email"; then
      dokku_log_warn "Failed to send email to '$email'"
  fi
done < "$EMAILS_FILE"
